{% set name = "stack_data" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cb2aff8164a81901160078ea2f5e39de978f08c96ac69e552a5c5345f892a81

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=44
    - setuptools_scm>=3.4.3
  run:
    - asttokens
    - executing
    - pure_eval
    - python >=3.6

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/alexmojaki/stack_data
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Extract data from python stack frames and tracebacks for informative displays
  doc_url: http://github.com/alexmojaki/stack_data
  dev_url: http://github.com/alexmojaki/stack_data

extra:
  recipe-maintainers:
    - alexmojaki
